easy_admin:
    site_name: 'Trad Practise'
    design:
        assets:
            js:
                - 'js/select2override.js'
        menu:
            - { label: 'Front', route: 'search_practises' }
            - { entity: 'Tune', params: { sortField: 'name', sortDirection: 'ASC' } }
            - TuneFile
            - TuneSet
            - PractiseSession
            - Technique
            - TechniqueFile
            - TuneType
            - TuneFileType
            - TechniqueType
            - TechniqueFileType
            - Tag
            - User
    list:
        max_results: 50
    entities:
        PractiseSession:
            class: AppBundle\Entity\PractiseSession
        Technique:
            class: AppBundle\Entity\Technique
            list:
                fields:
                    - name
                    - { property: 'exampleLink', template: 'url' }
                    - description
                    - techniqueType
                    - techniqueFiles

        TechniqueFile:
            class: AppBundle\Entity\TechniqueFile
            list:
                fields:
                    - name
                    - { property: 'link', template: 'url' }
                    - techniqueFileType
                    - technique
                    - { property: 'fileName', template: 'fileLink', base_path: %app.path.tune_file_path% }
            form:
                fields:
                    - name
                    - link
                    - techniqueFileType
                    - technique
                    - { property: 'file', type: 'vich_file' }
        TechniqueFileType:
            class: AppBundle\Entity\TechniqueFileType
        TechniqueType:
            class: AppBundle\Entity\TechniqueType
            form:
                fields:
                    - name
        Tune:
            class: AppBundle\Entity\Tune
            list:
                fields:
                    - name
                    - { property: 'linkTheSession', template: 'url', label: 'thesession' }
                    - key
                    - tuneType
                    - tuneFiles
                    - isStared
                    - tags
                    - { property: 'hasAbc', template: 'boolean' }
                    - { property: 'hasPartition', template: 'boolean' }
                    - { property: 'hasTuneSet', template: 'boolean' }
                actions: ['getAbc']
            form:
                fields:
                    - name
                    - { property: 'linkTheSession', template: 'url' }
                    - key
                    - abc
                    - tuneType
                    - isStared
                    - tags
        TuneFile:
            class: AppBundle\Entity\TuneFile
            list:
                fields:
                    - name
                    - { property: 'link', template: 'url' }
                    - tuneFileType
                    - tune
                    - mandolinTabId
                    - { property: 'fileName', template: 'fileLink', base_path: %app.path.tune_file_path% }
            form:
                fields:
                    - name
                    - link
                    - tuneFileType
                    - tune
                    - mandolinTabId
                    - { property: 'file', type: 'vich_file' }
        TuneFileType:
            class: AppBundle\Entity\TuneFileType
            list:
                fields:
                    - name
                    - { property: 'fileName', template: 'fileLink', base_path: %app.path.tune_file_path% }
            form:
                fields:
                    - name
                    - { property: 'file', type: 'vich_file' }
        TuneSet:
            class: AppBundle\Entity\TuneSet
            list:
                fields:
                    - { property: 'tune1'}
                    - { property: 'tune2'}
                    - { property: 'tune3'}
                    - { property: 'tune4'}
                    - { property: 'tune5'}
            form:
                fields:
                    - tune1
                    - tune2
                    - tune3
                    - tune4
                    - tune5
        TuneType:
            class: AppBundle\Entity\TuneType
        Tag:
            class: AppBundle\Entity\Tag
        User:
            class: AppBundle\Entity\User
