imports:
    - { resource: config_dev.yml }

parameters:
    database_host: qualif.kitfiscal.expertim.dev.a5sys.com
    database_name: kit_fiscal
    database_user: utest_kitfiscal
    database_password: utest_kitfiscal    
    
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
